### ISSUE TITLE
遗留xmind清理

### ISSUE THREAD

**Issue by BakaRice** [GUODnuli/Testlist-Conversation#1]
你好 朋友，你这里的航天一院-武器部-数据增广-图像增广 的测试用例过于显眼

建议仓库设置private 或者重新上传整个仓库
[武器部630交付需求.xmind](https://github.com/GUODnuli/Testlist-Conversation/commit/837dc793fa2b64275e936d5fe191c8aa8a0418b1)

**Comment by GUODnuli** [comment]
感谢提醒，后续会处理。
